#!/bin/bash
# Tor Party Line — Container Entrypoint
# Generates torrc from saved config, starts Tor as 'debian-tor' user (the reliable way),
# waits for bootstrap, then execs partyline.sh.
#
# Uses the exact permission+user pattern that makes Tor start reliably in Docker.

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# 1. Idempotent permission setup
#    Works on fresh bind mounts AND pre-populated bind mounts with existing keys.
#    Failure here means ./data/docker/tor was created by root (e.g. a prior
#    'sudo docker compose' run). Fix it on the host:
#        sudo chown -R "$USER":"$USER" ./data/docker/tor
#    or if this is a first run with no keys to keep:
#        sudo rm -rf ./data/docker/tor
# ─────────────────────────────────────────────────────────────────────────────
if ! chmod 700 /var/lib/tor 2>/dev/null; then
    _uid=$(stat -c '%u' /var/lib/tor 2>/dev/null || echo '?')
    printf '\n[!] Cannot set permissions on /var/lib/tor (owned by UID %s).\n' "$_uid" >&2
    printf '    Most likely cause: a prior run with sudo created the host directory as root.\n' >&2
    printf '    Fix on the host:\n' >&2
    printf '        sudo chown -R "$USER":"$USER" ./data/docker/tor\n' >&2
    printf '    Or if no keys exist yet, simply delete and rerun:\n' >&2
    printf '        sudo rm -rf ./data/docker/tor && docker compose run --rm partyline\n' >&2
    exit 1
fi
chown -R debian-tor:debian-tor /var/lib/tor
mkdir -p /var/lib/tor/hidden_service
chmod 700 /var/lib/tor/hidden_service
chown -R debian-tor:debian-tor /var/lib/tor/hidden_service

# Fix key permissions if keys already exist (from a prior run)
for _f in hs_ed25519_secret_key hs_ed25519_public_key; do
    _fp="/var/lib/tor/hidden_service/$_f"
    if [ -f "$_fp" ]; then
        chmod 600 "$_fp"
        chown debian-tor:debian-tor "$_fp"
    fi
done

# ─────────────────────────────────────────────────────────────────────────────
# 2. Create partyline data directories
# ─────────────────────────────────────────────────────────────────────────────
mkdir -p /data/.partyline/pids \
         /data/.partyline/audio \
         /data/.partyline/run \
         /data/.partyline/relay

# ─────────────────────────────────────────────────────────────────────────────
# 3. Generate torrc dynamically from saved config
#    This replicates what partyline.sh's setup_tor() + start_tor() does:
#    reading current settings and writing a fresh torrc each startup.
#    Ensures ExcludeNodes, SINGLE_HOP, SHOW_CIRCUIT all take effect correctly.
# ─────────────────────────────────────────────────────────────────────────────

# Defaults (may be overridden by saved config or docker-compose environment)
LISTEN_PORT="${LISTEN_PORT:-7777}"
EXCLUDE_NODES=""
SNOWFLAKE_ENABLED=0
SINGLE_HOP=0
SHOW_CIRCUIT=0

# Load saved settings from prior run (if config file exists).
# Parse key=value pairs explicitly — never source the file, as it lives on a
# user-controlled bind mount and sourcing executes arbitrary code as root.
if [ -f /data/.partyline/config ]; then
    while IFS= read -r _ep_line; do
        case "$_ep_line" in ''|'#'*) continue ;; esac
        _ep_key="${_ep_line%%=*}"
        _ep_raw="${_ep_line#*=}"
        # Strip one layer of surrounding double or single quotes, then unescape \" → "
        if [[ "$_ep_raw" == \"*\" ]]; then
            _ep_val="${_ep_raw:1:${#_ep_raw}-2}"
            _ep_val="${_ep_val//\\\"/\"}"
        elif [[ "$_ep_raw" == \'*\' ]]; then
            _ep_val="${_ep_raw:1:${#_ep_raw}-2}"
        else
            _ep_val="$_ep_raw"
        fi
        case "$_ep_key" in
            LISTEN_PORT)       LISTEN_PORT="$_ep_val" ;;
            EXCLUDE_NODES)     EXCLUDE_NODES="$_ep_val" ;;
            SNOWFLAKE_ENABLED) SNOWFLAKE_ENABLED="$_ep_val" ;;
            SINGLE_HOP)        SINGLE_HOP="$_ep_val" ;;
            SHOW_CIRCUIT)      SHOW_CIRCUIT="$_ep_val" ;;
        esac
    done < /data/.partyline/config
fi

TORRC=/tmp/partyline.torrc

# Search for GeoIP files (enables country names in circuit display)
GEOIP_LINE=""
GEOIP6_LINE=""
for _gdir in "/usr/share/tor" "/usr/local/share/tor"; do
    if [ -f "$_gdir/geoip" ]; then
        GEOIP_LINE="GeoIPFile $_gdir/geoip"
        [ -f "$_gdir/geoip6" ] && GEOIP6_LINE="GeoIPv6File $_gdir/geoip6"
        break
    fi
done

# SocksPort: disabled in single-hop mode (sacrifices server anonymity for speed)
if [ "${SINGLE_HOP:-0}" = "1" ]; then
    _SOCKS_LINE="SocksPort 0"
    _SH_LINES="HiddenServiceSingleHopMode 1
HiddenServiceNonAnonymousMode 1"
else
    _SOCKS_LINE="SocksPort 127.0.0.1:9050"
    _SH_LINES="HiddenServiceSingleHopMode 0
HiddenServiceNonAnonymousMode 0"
fi

cat > "$TORRC" << EOF
# Tor Party Line — generated by entrypoint.sh
# Do not edit; regenerated on each container start from /data/.partyline/config

DataDirectory /var/lib/tor
User debian-tor
${_SOCKS_LINE}

# Hidden Service — receives inbound calls at .onion:${LISTEN_PORT}
HiddenServiceDir /var/lib/tor/hidden_service/
HiddenServicePort ${LISTEN_PORT} 127.0.0.1:${LISTEN_PORT}
HiddenServiceVersion 3
${_SH_LINES}

# ── DoS Defenses (from tor-hidden-service-main) ──────────────────────────────

# Proof-of-Work: imposes client cost during overload; mitigates OnionFlation
HiddenServicePoWDefensesEnabled 1
HiddenServicePoWQueueRate 250
HiddenServicePoWQueueBurst 50000

# Intro point rate limiting
HiddenServiceEnableIntroDoSDefense 1
HiddenServiceEnableIntroDoSRatePerSec 25
HiddenServiceEnableIntroDoSBurstPerSec 200

# Per-circuit stream limits (close entire circuit on overflow → higher attacker cost)
HiddenServiceMaxStreams 50
HiddenServiceMaxStreamsCloseCircuit 1

# ── Anti-fingerprinting ───────────────────────────────────────────────────────
AvoidDiskWrites 1
DisableDebuggerAttachment 1
ConnectionPadding 1
ReducedConnectionPadding 0
CircuitPadding 1
ReducedCircuitPadding 0
HardwareAccel 0

# ── Circuit reliability ───────────────────────────────────────────────────────
NumEntryGuards 4
NumDirectoryGuards 3
MaxClientCircuitsPending 32
KeepalivePeriod 60 seconds
HeartbeatPeriod 30 minutes

# ── Control port (for circuit display in partyline.sh) ───────────────────────
# Always enabled — partyline.sh reads /var/lib/tor/control_auth_cookie
ControlPort 127.0.0.1:9051
CookieAuthentication 1

# ── Logging ───────────────────────────────────────────────────────────────────
# Log to file so we can monitor bootstrap progress
Log notice file /tmp/tor-bootstrap.log

EOF

# Append GeoIP file paths if found on this image
[ -n "$GEOIP_LINE" ]  && echo "$GEOIP_LINE"  >> "$TORRC"
[ -n "$GEOIP6_LINE" ] && echo "$GEOIP6_LINE" >> "$TORRC"

# Append ExcludeNodes if the user configured them in settings
if [ -n "${EXCLUDE_NODES:-}" ]; then
    echo "" >> "$TORRC"
    echo "ExcludeNodes ${EXCLUDE_NODES}" >> "$TORRC"
    echo "StrictNodes 1" >> "$TORRC"
fi

# Snowflake: not available in Docker mode (binary not included)
if [ "${SNOWFLAKE_ENABLED:-0}" = "1" ]; then
    echo "" >&2
    echo "┌─────────────────────────────────────────────────────┐" >&2
    echo "│ WARNING: Snowflake is not supported in Docker mode  │" >&2
    echo "│ Run partyline.sh on the host to use Snowflake        │" >&2
    echo "└─────────────────────────────────────────────────────┘" >&2
    echo "" >&2
fi

# Set permissions so Tor (running as 'debian-tor' user) can read the config
chown root:debian-tor "$TORRC"
chmod 644 "$TORRC"

# ─────────────────────────────────────────────────────────────────────────────
# 4. Start Tor — it drops to 'debian-tor' itself via the 'User debian-tor' torrc directive.
#    Running tor as root then letting it self-drop is the standard pattern for
#    system Tor packages and avoids needing 'su' or 'runuser' in the container.
# ─────────────────────────────────────────────────────────────────────────────
# Create log file so Tor can write to it after dropping privileges.
# Tor runs as 'debian-tor' and writes its log via 'Log notice file /tmp/tor-bootstrap.log'
# in the torrc. Do NOT redirect stdout/stderr here — that would conflict.
touch /tmp/tor-bootstrap.log
chown debian-tor:debian-tor /tmp/tor-bootstrap.log
tor -f "$TORRC" &
_TOR_BG=$!

printf "\n[+] Tor starting" >&2

# ─────────────────────────────────────────────────────────────────────────────
# 5. Wait for bootstrap — poll the log file for "Bootstrapped 100%"
# ─────────────────────────────────────────────────────────────────────────────
_WAITED=0
_TIMEOUT=180
_LAST_PROG=""

while [ $_WAITED -lt $_TIMEOUT ]; do
    # Check Tor process is still alive
    if ! kill -0 "$_TOR_BG" 2>/dev/null; then
        printf "\n\n[!] Tor process died. Log:\n" >&2
        cat /tmp/tor-bootstrap.log >&2
        exit 1
    fi

    if grep -q "Bootstrapped 100%" /tmp/tor-bootstrap.log 2>/dev/null; then
        printf "\n[+] Tor bootstrapped!\n" >&2
        break
    fi

    # Show live bootstrap progress (use -Eo not -oP: BusyBox grep has no -P)
    _PROG=$(grep -Eo 'Bootstrapped [0-9]+%[^:]*' /tmp/tor-bootstrap.log 2>/dev/null | tail -1 || true)
    if [ -n "$_PROG" ] && [ "$_PROG" != "$_LAST_PROG" ]; then
        printf "\r    %s          " "$_PROG" >&2
        _LAST_PROG="$_PROG"
    fi

    sleep 1
    _WAITED=$((_WAITED + 1))
done

if [ $_WAITED -ge $_TIMEOUT ]; then
    printf "\n[!] Tor bootstrap timed out after %ds\n" "$_TIMEOUT" >&2
    cat /tmp/tor-bootstrap.log >&2
    exit 1
fi

# ─────────────────────────────────────────────────────────────────────────────
# 6. Wait for hidden service hostname file
#    Tor writes this after publishing the hidden service descriptor
# ─────────────────────────────────────────────────────────────────────────────
_WAITED=0
while [ ! -f /var/lib/tor/hidden_service/hostname ] && [ $_WAITED -lt 20 ]; do
    sleep 1
    _WAITED=$((_WAITED + 1))
done

if [ -f /var/lib/tor/hidden_service/hostname ]; then
    _ONION=$(cat /var/lib/tor/hidden_service/hostname)
    printf "[+] Your address: %s\n\n" "$_ONION" >&2
else
    printf "[!] Hostname not yet written — partyline will show 'pending'\n\n" >&2
fi

# ─────────────────────────────────────────────────────────────────────────────
# 7. Exec into partyline.sh
#    `exec` replaces this shell so partyline.sh receives signals directly.
#    Tor continues running as a background process (not a child of partyline.sh).
# ─────────────────────────────────────────────────────────────────────────────
exec /partyline.sh "$@"
